In [1]:
set_a={1,2,3,4,5,}
set_b={3,6,7,9,8,10}
set_b.union(set_a)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [2]:
set_a.update([4,8,3,11])

In [3]:
set_a

{1, 2, 3, 4, 5, 8, 11}

In [4]:
def ret_sum(A):
    s=0
    for i in A:
        s=s+i
    return s
a=[1,2,3,4,5,6,7,8,9,10]
s=ret_sum(a)
print(s)

55


In [5]:
pointer=open('./First.txt','r')

In [6]:
type(pointer)

_io.TextIOWrapper

In [7]:
con=pointer.read()
con

'This is not HarshNew line is added'

In [8]:
pointer.close()

In [9]:
p2=open('./First.txt','w+')

In [10]:
p2.write("This is not Harsh")

17

In [11]:
p2.close()

In [12]:
p=open('./First.txt','r')


In [13]:
p.read()

'This is not Harsh'

In [14]:
p.close()

In [15]:
p2=open('./First.txt','a')


In [16]:
p2.write('New line is added')

17

In [17]:
p2.close()


In [18]:
p=open('./First.txt','r')
p.read()

'This is not HarshNew line is added'

In [19]:
import numpy as np

In [20]:
df = np.array([1,2,3,4,5,6])

In [21]:
df

array([1, 2, 3, 4, 5, 6])

In [22]:
type(df)

numpy.ndarray

In [23]:
df.shape

(6,)

In [24]:
df2=np.array([[1,2,3,4,5],[11,12,13,14,15]])
df2

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [25]:
df2.ndim

2

In [26]:
df2.shape

(2, 5)

In [27]:
df2.sum()

80

In [28]:
df2.sum(axis=1)

array([15, 65])

In [31]:
ran_array=np.random.random(size=(3,4))

In [32]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.full(shape=(2,3),fill_value=22)

array([[22, 22, 22],
       [22, 22, 22]])

In [37]:
ran_array


array([[6.43841394e-01, 9.39580299e-02, 2.63417152e-01, 4.61777934e-01],
       [3.76471808e-01, 3.73270282e-01, 2.25260482e-01, 4.90936237e-04],
       [7.74486987e-01, 2.24874056e-01, 6.65478345e-01, 4.07183785e-01]])

In [39]:
#Transpose
ran_array.T

array([[6.43841394e-01, 3.76471808e-01, 7.74486987e-01],
       [9.39580299e-02, 3.73270282e-01, 2.24874056e-01],
       [2.63417152e-01, 2.25260482e-01, 6.65478345e-01],
       [4.61777934e-01, 4.90936237e-04, 4.07183785e-01]])

In [40]:
ran_sq=np.random.random(size=(4,4))

In [41]:
ran_sq

array([[0.23087381, 0.55360884, 0.32901844, 0.50788441],
       [0.59931022, 0.70869309, 0.22386845, 0.34603643],
       [0.89772466, 0.83837095, 0.11863331, 0.33534309],
       [0.68379924, 0.90695933, 0.82676079, 0.12208925]])

In [44]:
ident=np.identity(4)

In [45]:
ident


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
np.dot(ident,ran_sq)

array([[0.23087381, 0.55360884, 0.32901844, 0.50788441],
       [0.59931022, 0.70869309, 0.22386845, 0.34603643],
       [0.89772466, 0.83837095, 0.11863331, 0.33534309],
       [0.68379924, 0.90695933, 0.82676079, 0.12208925]])

In [48]:
Inv_sq=np.linalg.inv(ran_sq)

In [49]:
np.dot(Inv_sq,ran_sq)

array([[ 1.00000000e+00, -4.02178205e-15, -6.10087451e-16,
        -1.66716777e-15],
       [-2.75331144e-17,  1.00000000e+00, -1.02102212e-15,
         1.31590067e-15],
       [ 1.67891650e-15,  1.05204766e-15,  1.00000000e+00,
        -2.83188476e-16],
       [ 8.07470384e-16,  3.01942693e-16,  4.01520818e-16,
         1.00000000e+00]])

In [50]:
arr3=np.random.random(size=(3,4))

In [51]:
arr3

array([[0.99351662, 0.29950418, 0.612129  , 0.34089763],
       [0.53090925, 0.79151662, 0.13111964, 0.74919357],
       [0.0608211 , 0.02369661, 0.13405694, 0.08594338]])

In [52]:
arr3+ 3

array([[3.99351662, 3.29950418, 3.612129  , 3.34089763],
       [3.53090925, 3.79151662, 3.13111964, 3.74919357],
       [3.0608211 , 3.02369661, 3.13405694, 3.08594338]])

In [55]:
arr5=np.full(shape=(3,4),fill_value=5)